# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hannah Fell
email: hannah@hannahfell.com
description: >- # this means to ignore newlines until "baseurl:"
  Hannah Fell <br>
  The Doyle Group <br>
  Associate Editor <br>
  -  Chiropractic Economics <br>
  -  MASSAGE Magazine

baseurl: "" # the subpath of your site, e.g. /blog
url: "www.hannahfell.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hcfell
linkedin_username: hannah-fell-b2333ab121

social_links:
    Twitter: https://twitter.com/hcfell
    LinkedIn: https://www.linkedin.com/in/hannah-fell-b2333ab121

# Build settings
markdown: kramdown
theme: alembic-jekyll-theme
plugins:
  - jekyll-feed
  - jekyll-paginate-v2

collections:
  stories:
    output: true
    permalink: /portfolio/stories/:title/
  clips:
    output: true
    permalink: /portfolio/clips/:title/

navigation_header:
  Home: /
  Portfolio: /portfolio/
  Blog: /blog/
  About: /about/

navigation_footer:
   Hannah Fell:

permalink: pretty

pagination: 
  enabled: true
  per_page: 10
  permalink: "/blog/:num/"
  title: " - blog :num"
  limit: 0
  sort_field: "date"
  sort_reverse: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/